### ISSUE TITLE
No results returned [patch]

### ISSUE THREAD

**Issue by mattbeedle** [jugyo/sunspot_mongoid#1]
I tried installing this with the latest version of sunspot, rails 3 and mongoid, but no results were returned.  Solr was returning the correct results, but because ObjectIDs where not used in the adapters #load_all method, nothing was loaded.

Here is the fix:

http://github.com/mattbeedle/sunspot_mongoid/tree/object_ids

**Comment by jugyo** [comment]
Thanks!
I have applied it now.
