### ISSUE TITLE
Can't use Model.search 

### ISSUE THREAD

**Issue by parano** [jugyo/sunspot_mongoid#17]
I set up Sunspot follow this https://github.com/sunspot/sunspot document, and when i type  Post.search { fulltext 'text' }, it gives me this error message:

```
Mongoid::Errors::InvalidFind: Calling Document#find with nil is invalid
```

when i change it to Model.solr_search or Sunspot.search(Post)  , the `.result` always give me an empty array . 

I've asked this question here http://stackoverflow.com/questions/8654329/how-to-make-sunspot-works-with-mongoid-rails-3  , but no one answers me . and my project source code was here https://github.com/sunspot/sunspot

**Comment by yury** [comment]
Use prefixed method. Mongoid define it's own search method

```
Model.solr_search
```

And I use https://github.com/TV4/sunspot_mongoid fork

**Comment by parano** [comment]
these one really works, thank you very much .
