### ISSUE TITLE
Please update your gem on gemcutter.org

### ISSUE THREAD

**Issue by aq1018** [jugyo/sunspot_mongoid#6]
Hi, Since the ObjectID has been deprecated in mongo-ruby-driver 1.0.8 and now the repo changed to use ObjectId as well, this warrants a new version with newer decencies on mongo-ruby-driver. Could please push this new version to gemcutter.org? Thanks!

**Comment by jugyo** [comment]
I will do that.
Please wait.

**Comment by jugyo** [comment]
The new gem (0.4.0) had been pushed to rubygems.org already.
Could you try it?

**Comment by aq1018** [comment]
Thanks! That was fast! I did work. However, I did some fixes and sent you a pull request please check...
